package com.calculadora.service;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;









@DynamoDBTable(tableName="Calculadora")
public class Calculadora
{
  @DynamoDBHashKey(attributeName="Id")
  @DynamoDBAutoGeneratedKey
  private String id;
  @DynamoDBHashKey(attributeName="Valor1")
  private double valor1;
  @DynamoDBHashKey(attributeName="Valor2")
  private double valor2;
  @DynamoDBHashKey(attributeName="Resultado")
  private double resultado;
  @DynamoDBIndexHashKey(attributeName="Operacao", globalSecondaryIndexName="Operacao-index")
  private String operacao;
  
  public Calculadora() {}
  
  public Calculadora(String id, double valor1, double valor2, String operacao)
  {
    this.id = id;
    this.valor1 = valor1;
    this.valor2 = valor2;
    this.operacao = operacao;
  }
  
  public void setOperacao(String operacao) {
    this.operacao = operacao;
  }
  
  public String getId() {
    return id;
  }
  
  public void setId(String id) {
    this.id = id;
  }
  
  public double getValor1() {
    return valor1;
  }
  
  public void setValor1(double valor1) {
    this.valor1 = valor1;
  }
  
  public double getValor2() {
    return valor2;
  }
  
  public void setValor2(double valor2) {
    this.valor2 = valor2;
  }
  
  public String getOperacao() {
    return operacao;
  }
  
  public double getResultado() {
    return resultado;
  }
  
  public void setResultado(double resultado) {
    this.resultado = resultado;
  }
  
  public double soma()
  {
    return valor1 + valor2;
  }
  


  public double subtrair()
  {
    return valor1 - valor2;
  }
  

  public double multiplicar()
  {
    return valor1 * valor2;
  }
  
  public double dividir()
  {
    return valor1 / valor2;
  }
}